### ISSUE TITLE
Error installing pynoco: missing requirements.txt in package

### ISSUE THREAD

**Issue by mohamedmeqlad99** [TalaatHasanin/nocodb-python-client#1]
When attempting to install `pynoco` using pip, I encounter the following error:

Defaulting to user installation because normal site-packages is not writeable Collecting pynoco Using cached pynoco-1.0.0.tar.gz (5.0 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [7 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-0k48jy25/pynoco_52672f16a1fd41b3b9b9613854c94f78/setup.py", line 10, in <module> with open('requirements.txt') as req_file: ^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt' [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed

It seems the package is trying to open a `requirements.txt` file that is not included in the package distribution.

**Steps to reproduce**:
1. Run `pip install pynoco`

**Expected behavior**:
The package should install successfully without errors.

**Actual behavior**:
The installation fails due to a missing `requirements.txt` file.

**Comment by TalaatHasanin** [comment]
Thanks @mohamedmeqlad99 
will check out
